const school = [
  { month: 5, year: 2026, workingDays: 22, events: { 1: ['School Reopens after summer vacation for classes VI - XII'], 2: ['Parents Conference VI & VII'], 3: ['School Reopens for classes I - V', 'Parents Conference VIII'], 4: ['School Reopens for Sr KG', 'Parents Conference IX'], 5: ['World Environment Day', 'Secondary Bagless Day', 'Parents Conference X & XII'], 6: ['Parents Conference X & XII'], 7: ['Holiday'], 8: ['School Reopens for Jr KG'], 10: ['School Reopens for Pre KG & Class XI', 'Parents Conference Class XI'], 13: ['Second Saturday Holiday'], 14: ['Holiday'], 16: ['Periodic test 1 for class X & XII'], 19: ['National Reading Day'], 21: ['International Yoga Day Holiday'], 22: ['Middle Section Bagless Day'], 23: ['Inspiro - School Level'], 24: ['LP - Bagless Day'], 25: ['Holiday (Muharram)'], 26: ['International Anti Drug Day'], 28: ['Holiday'], 29: ['English Fest - School Level'] } },
  { month: 6, year: 2026, workingDays: 25, events: { 1: ['National Doctors Day'], 2: ['Inspiro 2026 - Cluster level competition'], 5: ['Basheer Day Holiday'], 6: ['Club Activity Senior Secondary - Bagless day'], 8: ['LEAP Preliminary'], 11: ['Second Saturday Holiday'], 12: ['Holiday'], 13: ['Pre-Midterm Assessment for classes I to XII'], 16: ['IECI Teachers Conference'], 19: ['Holiday'], 20: ['International Moon Day'], 25: ['National Anti Narcotic Day'], 26: ['Holiday'], 27: ['School Parliament Election, Middle Section Bagless Day'], 29: ['Chess Tournament State Level, Creative Fest - Inauguration'], 30: ['Creative Fest - Sr. Secondary'], 31: ['Creative Fest - Secondary', 'LP - Bagless Day'] } },
  { month: 7, year: 2026, workingDays: 23, events: { 2: ['Holiday'], 3: ['Creative Fest - Middle, Middle Section Bagless Day'], 4: ['Inspiro 2026 State Level Competition'], 5: ['Creative Fest - Primary Bagless Day'], 6: ['Hiroshima Day, Creative Fest - Primary Bagless Day'], 7: ['Open Day 1'], 8: ['Quit India Day, Second Saturday Holiday'], 9: ['Holiday'], 10: ['Investiture Ceremony'], 11: ['English Fest 2026 State Level'], 12: ['Holiday (Karkkidakavavu)'], 15: ['Independence Day (Holiday)'], 16: ['Holiday'], 17: ['Periodic Test 2 classes X & XII, Farmers Day'], 19: ['World Photography Day'], 20: ['Bagless Day (Primary)', 'LP - Bagless Day'], 23: ['Onam Holidays'], 24: ['Onam Holidays'], 25: ['Onam Holidays', 'Milad-E-Sharif (Holiday)'], 26: ['Onam Holidays'], 27: ['Onam Holidays'], 28: ['Onam Holidays, Sree Narayana Guru Jayanthi/Ayyankali Jayanthi'], 29: ['National Sports Day, Onam Holidays'], 30: ['Onam Holidays'], 31: ['School Reopens after Onam Holidays'] } },
  { month: 8, year: 2026, workingDays: 21, events: { 4: ['Sree Krishna Jayanthi Holiday'], 5: ['National Teachers Day, Secondary Bagless Day'], 6: ['Holiday'], 7: ['Middle Section Bagless Day'], 8: ['International Literacy Day'], 9: ['LP - Bagless Day'], 12: ['First Aid Day - Second Saturday Holiday'], 13: ['Holiday'], 14: ['National Hindi Day'], 17: ['LEAP 2026'], 20: ['Holiday'], 21: ['Holiday (Sreenarayana Guru Samadhi)'], 27: ['Holiday'], 29: ['Midterm Assessment Begins for classes I - XII'] } },
  { month: 9, year: 2026, workingDays: 23, events: { 2: ['Gandhi Jayanthi (Holiday)'], 4: ['Holiday'], 6: ['Bagless day - LP', 'Bagless day - Middle section'], 10: ['National Postal Day Second Saturday (Holiday)'], 11: ['Holiday'], 13: ['Annual Sports Inauguration - Sr. Secondary & Secondary'], 14: ['Bagless Day, Annual Sports - Middle'], 15: ['Annual Sports - Primary'], 16: ['World Food Day, Annual Sports - LP'], 18: ['Holiday'], 19: ['Annual Sports - Sprouts'], 20: ['Mahanavami (Holiday)'], 21: ['Vijayadashmi (Holiday)'], 24: ['UN Day, Open Day 2'], 25: ['Holiday'], 31: ['National Unity Day'] } },
  { month: 10, year: 2026, workingDays: 24, events: { 1: ['Kerala Piravi Day'], 3: ['Middle Section, Bagless Day'], 4: ['Class XII Tour - Bagless'], 7: ['IECI Kids Fest'], 8: ['Diwali Holiday'], 11: ['National Education Day'], 14: ['Second Saturday Children’s Day'], 15: ['Holiday'], 17: ['Middle Section Bagless Day'], 18: ['IECI Athletic Meet'], 19: ['IECI Athletic Meet'], 22: ['Holiday'], 25: ['Digital Fest'], 26: ['Constitution Day'], 28: ['Club Activity Senior Secondary Bagless day'] } },
  { month: 11, year: 2026, workingDays: 20, events: { 1: ['Football Tournament Zone 2'], 2: ['Football Tournament Zone 2'], 3: ['International Day of Persons with Disability'], 5: ['IECI Kids Sports'], 6: ['Holiday'], 8: ['Football Tournament - Final'], 9: ['Football Tournament - Final'], 10: ['World Human Rights Day, Post Midterm Assessment begins for classes I - XII'], 12: ['Second Saturday (Holiday)'], 13: ['Holiday'], 14: ['XI - Tour Bagless day'], 18: ['World Arabic Language Day'], 20: ['Winter Break'], 21: ['Winter Break'], 22: ['National Mathematics Day Winter Break'], 23: ['Winter Break'], 24: ['Winter Break'], 25: ['Christmas Holiday'], 26: ['Winter Break'], 27: ['Winter Break'], 29: ['Class Magazine Release'], 31: ['Interschool Digital Fest'] } },
  { month: 0, year: 2027, workingDays: 23, events: { 1: ['New Year'], 2: ['Mannam Jayanth (Holiday)'], 3: ['Holiday'], 6: ['Grand Parents Day - Class 2 Creative Fest'], 7: ['Middle section Bagless Day'], 9: ['Second Saturday (Holiday), Secondary Bagless Day'], 10: ['Holiday'], 12: ['Parents Day - Class 1 Creative Fest'], 14: ['Kids Fest - Sr. KG'], 16: ['Open Day 3'], 17: ['Holiday'], 19: ['Pre-Board Exams for classes X & XII'], 23: ['Grand Parents Day - Jr. KG, Club Activity Senior Secondary Bagless day'], 24: ['Holiday'], 26: ['Republic Day (Holiday)'], 28: ['School Annual Day'], 30: ['Martyrs Day, Sr. KG Convocation'], 31: ['Holiday'] } },
  { month: 1, year: 2027, workingDays: 23, events: { 5: ['Cyber Security Day'], 7: ['Holiday'], 9: ['Ramadan Commence'], 13: ['Second Saturday (Holiday)'], 14: ['Holiday'], 16: ['Annual Exam begins for classes IX & XI'], 21: ['Holiday'], 28: ['National Science Day'] } },
  { month: 2, year: 2027, workingDays: 22, events: { 6: ['Maha Shivaratri, Idul Fitr Holiday'], 7: ['Idul Fitr Holiday'], 8: ['International Women’s Day, Idul Fitr Holiday'], 9: ['Idul Fitr Holiday'], 10: ['Idul Fitr Holiday'], 11: ['Classes reopens after Idul Fitr'], 13: ['Second Saturday (Holiday)'], 14: ['Holiday'], 18: ['Annual Exam Starts for classes I - VIII'], 25: ['Maundy Thursday Holiday'], 26: ['Good Friday Holiday'], 28: ['Easter'], 31: ['School Closes for Summer Vacation'] } }
];

const sprouts = [
  { month: 5, year: 2026, workingDays: 18, events: { 5: ['World Environment Day'], 6: ['Holiday'], 7: ['Holiday'], 8: ['School Begins for Jr KG'], 9: ['School Reopens for Sr KG'], 10: ['School Begins for Pre KG'], 12: ['Anti Child Labour Day'], 13: ['Second Saturday Holiday'], 14: ['Holiday'], 19: ['National Reading Day'], 20: ['Holiday'], 21: ['International Yoga Day Holiday'], 25: ['Muharam Holiday'], 26: ['Colours Day'], 27: ['Holiday'], 28: ['Holiday'] } },
  { month: 6, year: 2026, workingDays: 23, events: { 1: ['National Doctors Day'], 4: ['Holiday'], 5: ['Holiday'], 11: ['Second Saturday Holiday'], 12: ['Holiday'], 18: ['Holiday'], 19: ['Holiday'], 20: ['International Moon Day'], 25: ['Holiday'], 26: ['Holiday'], 30: ['Fruits Day'] } },
  { month: 7, year: 2026, workingDays: 15, events: { 1: ['Holiday'], 2: ['Holiday'], 8: ['Second Saturday Holiday'], 9: ['Holiday'], 12: ['Karkkidakavavu Holiday'], 15: ['Independence Day Holiday'], 16: ['Holiday'], 21: ['Flowers Day', 'School Closes for Onam Holidays'], 22: ['Holiday'], 23: ['Holiday'], 24: ['Onam Holiday'], 25: ['Milad-E-Sharif Onam Holiday'], 26: ['Onam Holiday'], 27: ['Onam Holiday'], 28: ['Sree Narayana Guru Jayanthi, Ayyankali Jayanthi Onam Holiday'], 29: ['Holiday'], 30: ['Holiday'], 31: ['School Reopens After Onam Holidays'] } },
  { month: 8, year: 2026, workingDays: 20, events: { 4: ['Sree Krishna Jayanthi Holiday'], 5: ['National Teachers day'], 6: ['Holiday'], 12: ['Second Saturday Holiday'], 13: ['Holiday'], 19: ['Holiday'], 20: ['Holiday'], 21: ['Sree Narayana Guru Samadhi Holiday'], 24: ['Busy Bee Day'], 26: ['Holiday'], 27: ['Holiday'], 29: ['1st Term Assessment Begins'] } },
  { month: 9, year: 2026, workingDays: 19, events: { 2: ['Gandhi Jayanthi Holiday'], 3: ['Holiday'], 4: ['Holiday'], 10: ['National Postal Day & Second Saturday Holiday'], 11: ['Holiday'], 16: ['World Food Day'], 17: ['Holiday'], 18: ['Holiday'], 19: ['Annual Sports Day'], 20: ['Mahanavami Holiday'], 21: ['Vijayadashami Holiday'], 24: ['Open Day'], 25: ['Holiday'], 31: ['Holiday'] } },
  { month: 10, year: 2026, workingDays: 21, events: { 1: ['Keralapiravi Holiday'], 7: ['IECI Kids Fest Holiday'], 8: ['Diwali Holiday'], 11: ['National Education Day'], 14: ['Children’s Day Holiday'], 15: ['Holiday'], 21: ['Holiday'], 22: ['Holiday'], 28: ['Holiday'], 29: ['Holiday'] } },
  { month: 11, year: 2026, workingDays: 18, events: { 5: ['IECI Kids Sports Holiday'], 6: ['Holiday'], 10: ['2nd Term Assessment begins'], 12: ['Second Saturday Holiday'], 13: ['Holiday'], 18: ['School closes for winter break'], 19: ['Holiday'], 20: ['Holiday'], 21: ['Winter Break'], 22: ['Winter Break'], 23: ['Winter Break'], 24: ['Winter Break'], 25: ['Christmas Holiday'], 26: ['Holiday'], 27: ['Holiday'], 28: ['School Reopens after winter break'] } },
  { month: 0, year: 2027, workingDays: 20, events: { 2: ['Mannam Jayanthi Holiday'], 3: ['Holiday'], 9: ['Holiday'], 10: ['Holiday'], 16: ['Open Day'], 17: ['Holiday'], 23: ['Annual Day - Sr KG'], 24: ['Holiday'], 26: ['Republic Day Holiday'], 30: ['Grandparents Day - Jr KG'], 31: ['Holiday'] } },
  { month: 1, year: 2027, workingDays: 20, events: { 6: ['Convocation - Sr KG'], 7: ['Holiday'], 9: ['Ramadan Commence'], 13: ['Second Saturday Holiday'], 14: ['Holiday'], 20: ['Holiday'], 21: ['Holiday'], 27: ['Holiday'], 28: ['Holiday'] } },
  { month: 2, year: 2027, workingDays: 18, events: { 5: ['School closes for Eid al-Fitr'], 6: ['Mahashivarathri Holiday'], 7: ['Eid al-Fitr Holiday'], 8: ['Eid al-Fitr Holiday'], 9: ['Eid al-Fitr Holiday'], 10: ['Classes Reopen After Eid al-Fitr'], 13: ['Second Saturday Holiday'], 14: ['Holiday'], 18: ['Annual Assessment Begins'], 20: ['Holiday'], 21: ['Holiday'], 25: ['Maundy Thursday Holiday'], 26: ['Good Friday Holiday'], 27: ['Holiday'], 28: ['Easter Holiday'], 31: ['School Closes For Summer Vacation'] } }
];

export const SCHOOL_ACADEMIC_CALENDAR = { audience: 'Ansar English School', weekStartsMonday: false, months: school };
export const SPROUTS_ACADEMIC_CALENDAR = { audience: 'Ansar Sprouts', weekStartsMonday: true, months: sprouts };

export function withSavedCalendarMonths(calendar, savedMonths) {
  return Array.isArray(savedMonths) && savedMonths.length === calendar.months.length
    ? { ...calendar, months: savedMonths }
    : calendar;
}
