import React, { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, serverTimestamp, setDoc, updateDoc, writeBatch } from 'firebase/firestore';
import { db } from './firebase-init';
import { formatDuration, googleExportUrl, loadGoogleSheetQuestions, normalizeAnswer, parseQuizText } from './quizUtils';

const EMPTY = { title: '', className: '1', division: '', durationMinutes: 30, sourceUrl: '', instructions: 'Answer every question. Accuracy comes first; ties are ranked by completion time.' };

export default function AdminQuizCorner() {
  const [form, setForm] = useState(EMPTY), [preview, setPreview] = useState([]), [quizzes, setQuizzes] = useState([]), [activeId, setActiveId] = useState('');
  const [participants, setParticipants] = useState([]), [quizQuestions, setQuizQuestions] = useState([]), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const active = quizzes.find(q => q.id === activeId) || null;

  useEffect(() => onSnapshot(collection(db, 'quizSessions'), snap => setQuizzes(snap.docs.map(d => ({ id: d.id, ...d.data() })).sort((a, b) => (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0)))), []);
  useEffect(() => { if (!activeId) return undefined; return onSnapshot(collection(db, 'quizSessions', activeId, 'participants'), snap => setParticipants(snap.docs.map(d => ({ id: d.id, ...d.data() })))); }, [activeId]);
  useEffect(() => { if (!activeId) { setQuizQuestions([]); return undefined; } return onSnapshot(collection(db, 'quizSessions', activeId, 'questions'), snap => setQuizQuestions(snap.docs.map(d => ({ id: d.id, ...d.data() })).sort((a, b) => a.order - b.order))); }, [activeId]);

  const importQuestions = async () => { setBusy(true); setMessage(''); try { let parsed = await loadGoogleSheetQuestions(form.sourceUrl); if (!parsed) { const response = await fetch(googleExportUrl(form.sourceUrl)); if (!response.ok) throw new Error(`Google returned HTTP ${response.status}. Confirm link access is enabled.`); parsed = parseQuizText(await response.text()); } if (!parsed.length) throw new Error('No valid questions were found.'); setPreview(parsed); setMessage(`${parsed.length} questions imported successfully.`); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const createQuiz = async e => { e.preventDefault(); if (!preview.length) return setMessage('Import at least one question first.'); setBusy(true); try {
    const ref = await addDoc(collection(db, 'quizSessions'), { title: form.title.trim(), className: form.className, division: form.division.trim().toUpperCase(), durationMinutes: Number(form.durationMinutes), instructions: form.instructions.trim(), sourceUrl: form.sourceUrl.trim(), status: 'draft', questionCount: preview.length, createdAt: serverTimestamp(), updatedAt: serverTimestamp() });
    const batch = writeBatch(db); preview.forEach((q, index) => { batch.set(doc(db, 'quizSessions', ref.id, 'questions', q.id), { question: q.question, options: q.options, type: q.type, order: index, points: q.points }); batch.set(doc(db, 'quizSessions', ref.id, 'answers', q.id), { answer: q.answer, normalizedAnswer: normalizeAnswer(q.answer) }); }); await batch.commit(); setForm(EMPTY); setPreview([]); setActiveId(ref.id); setMessage('Quiz created. Open the lobby when students are ready.');
  } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const setStatus = async status => { if (!active) return; await updateDoc(doc(db, 'quizSessions', active.id), { status, [`${status}At`]: serverTimestamp(), updatedAt: serverTimestamp() }); };
  const scoreSubmissions = async () => { if (!active) return; const answerSnap = await getDocs(collection(db, 'quizSessions', active.id, 'answers')); const key = Object.fromEntries(answerSnap.docs.map(d => [d.id, d.data().normalizedAnswer])); const batch = writeBatch(db); participants.filter(p => p.status === 'submitted').forEach(p => { const score = Object.entries(key).reduce((sum, [id, answer]) => sum + (normalizeAnswer(p.answers?.[id]) === answer ? 1 : 0), 0); const durationMs = Math.max(0, (p.submittedAt?.toMillis?.() || 0) - (p.startedAt?.toMillis?.() || 0)); batch.update(doc(db, 'quizSessions', active.id, 'participants', p.id), { score, total: Object.keys(key).length, durationMs, status: 'scored', updatedAt: serverTimestamp() }); }); await batch.commit(); };
  const scoreTimedOutSubmissions = async () => { if (!active) return; const targets = participants.filter(p => p.status === 'submitted' && p.timedOut === true); if (!targets.length) return; const answerSnap = await getDocs(collection(db, 'quizSessions', active.id, 'answers')); const key = Object.fromEntries(answerSnap.docs.map(d => [d.id, d.data().normalizedAnswer])); const batch = writeBatch(db); targets.forEach(p => { const score = Object.entries(key).reduce((sum, [id, answer]) => sum + (normalizeAnswer(p.answers?.[id]) === answer ? 1 : 0), 0); const durationMs = Math.max(0, (p.submittedAt?.toMillis?.() || 0) - (p.startedAt?.toMillis?.() || 0)); batch.update(doc(db, 'quizSessions', active.id, 'participants', p.id), { score, total: Object.keys(key).length, durationMs, status: 'scored', updatedAt: serverTimestamp() }); }); await batch.commit(); };
  useEffect(() => { if (participants.some(p => p.status === 'submitted' && p.timedOut === true)) scoreTimedOutSubmissions(); }, [activeId, participants.map(p => `${p.id}:${p.status}:${p.timedOut}`).join('|')]);
  useEffect(() => { if (active?.status === 'ended' && participants.some(p => p.status === 'submitted')) scoreSubmissions(); }, [active?.status, participants.map(p => `${p.id}:${p.status}`).join('|')]);
  const unlock = p => updateDoc(doc(db, 'quizSessions', active.id, 'participants', p.id), { status: active.status === 'running' ? 'waiting' : 'waiting', violation: '', unlockedAt: serverTimestamp(), updatedAt: serverTimestamp() });
  const ranked = useMemo(() => participants.filter(p => p.score != null).sort((a, b) => b.score - a.score || (a.durationMs || Infinity) - (b.durationMs || Infinity)).map((p, i) => ({ ...p, rank: i + 1 })), [participants]);
  const download = () => {
    if (!active) return;
    const timingHeaders = quizQuestions.map((_, index) => `Question ${index + 1} time seconds`);
    const ordered = [...ranked, ...participants.filter(p => p.score == null)];
    const rows = [['Rank','Name','Class','Division','Score','Total','Completion time seconds','Status','Violation', ...timingHeaders], ...ordered.map(p => [p.rank || '', p.name, p.className, p.division, p.score ?? '', p.total ?? '', p.durationMs == null ? '' : Math.round(p.durationMs / 1000), p.status, p.violation || '', ...quizQuestions.map(question => Math.round((p.questionTimings?.[question.id] || 0) / 1000))])];
    const csv = rows.map(row => row.map(v => `"${String(v ?? '').replace(/"/g,'""')}"`).join(',')).join('\r\n');
    const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = `${active.title.replace(/[^a-z0-9]+/gi,'-')}-results.csv`; link.click(); URL.revokeObjectURL(link.href);
  };
  const print = () => window.print();
  const complete = async () => { if (!window.confirm('Download results and permanently clear this quiz, its questions, answers, participants, timings, and violations?')) return; download(); setBusy(true); try { const [q, a, p] = await Promise.all([getDocs(collection(db, 'quizSessions', active.id, 'questions')), getDocs(collection(db, 'quizSessions', active.id, 'answers')), getDocs(collection(db, 'quizSessions', active.id, 'participants'))]); const refs = [...q.docs, ...a.docs, ...p.docs].map(item => item.ref); for (let i = 0; i < refs.length; i += 400) { const batch = writeBatch(db); refs.slice(i, i + 400).forEach(ref => batch.delete(ref)); await batch.commit(); } await deleteDoc(doc(db, 'quizSessions', active.id)); setActiveId(''); setParticipants([]); setMessage('Quiz and all corresponding Firestore data were cleared.'); } finally { setBusy(false); } };

  const field = 'mt-1 w-full rounded-xl border border-slate-200 p-3 outline-none focus:ring-2 focus:ring-indigo-500';
  return <div className="space-y-8">
    <section className="rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-50 to-cyan-50 p-6"><p className="text-xs font-black uppercase tracking-widest text-indigo-700">Interactive quiz control room</p><h2 className="mt-2 text-3xl font-black text-slate-900">Library Quiz Corner</h2><p className="mt-2 text-slate-600">Import, schedule, monitor, score, unlock, and export quizzes from one screen.</p></section>
    <label className="block rounded-2xl border border-indigo-100 bg-white p-5 text-sm font-bold shadow-sm">Quiz duration (minutes)<input required type="number" min="1" max="180" value={form.durationMinutes} onChange={e => setForm({...form,durationMinutes:e.target.value})} className={`${field} max-w-xs`} /><span className="mt-2 block font-normal text-slate-500">This duration is saved with the new quiz. Students see a synchronized countdown and their answers are submitted automatically at zero.</span></label>
    <form onSubmit={createQuiz} className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="text-xl font-black">Create a quiz</h3><div className="mt-5 grid gap-4 md:grid-cols-4"><label className="text-sm font-bold md:col-span-2">Quiz title<input required maxLength="120" value={form.title} onChange={e => setForm({...form,title:e.target.value})} className={field}/></label><label className="text-sm font-bold">Class<select value={form.className} onChange={e => setForm({...form,className:e.target.value})} className={field}>{Array.from({length:12},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><label className="text-sm font-bold">Division (optional)<input maxLength="5" value={form.division} onChange={e => setForm({...form,division:e.target.value})} className={field}/></label><label className="text-sm font-bold md:col-span-3">Google Sheets or Docs sharing link<input required type="url" value={form.sourceUrl} onChange={e => setForm({...form,sourceUrl:e.target.value})} className={field}/><span className="mt-1 block text-xs font-normal text-slate-500">Columns: Question, Option A, Option B, Option C, Option D, Answer. For fill-in answers, leave options blank.</span></label><button type="button" onClick={importQuestions} disabled={busy || !form.sourceUrl} className="self-end rounded-xl bg-cyan-600 p-3 font-black text-white disabled:opacity-40">Import questions</button></div>{message && <p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm font-bold">{message}</p>}{preview.length > 0 && <div className="mt-5"><p className="font-black">Preview ({preview.length})</p><ol className="mt-2 max-h-48 list-decimal overflow-auto pl-6 text-sm text-slate-600">{preview.map(q=><li key={q.id} className="py-1">{q.question} <span className="text-emerald-700">— {q.type}</span></li>)}</ol><button disabled={busy} className="mt-5 rounded-xl bg-indigo-700 px-6 py-3 font-black text-white">Save quiz as draft</button></div>}</form>
    <section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="text-xl font-black">Quiz sessions</h3><p className="text-sm text-slate-500">Select a quiz to open its live control room.</p></div><select value={activeId} onChange={e=>setActiveId(e.target.value)} className="rounded-xl border p-3"><option value="">Select quiz…</option>{quizzes.map(q=><option value={q.id} key={q.id}>{q.title} · Class {q.className} · {q.status}</option>)}</select></div>
      {active && <div className="mt-6"><div className="flex flex-wrap gap-2"><button onClick={()=>setStatus('lobby')} className="rounded-lg bg-amber-500 px-4 py-2 font-bold">Open lobby</button><button onClick={()=>setStatus('running')} className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white">Start quiz</button><button onClick={async()=>{await setStatus('ended');await scoreSubmissions()}} className="rounded-lg bg-slate-800 px-4 py-2 font-bold text-white">End & reveal scores</button><button onClick={download} className="rounded-lg border px-4 py-2 font-bold">Download CSV</button><button onClick={print} className="rounded-lg border px-4 py-2 font-bold">Print</button><button onClick={complete} className="rounded-lg bg-red-600 px-4 py-2 font-bold text-white">Mark completed & clear</button></div><p className="mt-4 text-sm font-bold">Status: <span className="uppercase text-indigo-700">{active.status}</span> · {participants.length} participants</p>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-100"><tr>{['Rank','Student','Class','Progress','Time','Score','Status','Action'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{participants.sort((a,b)=>(b.progress||0)-(a.progress||0)).map(p=>{const rank=ranked.find(r=>r.id===p.id)?.rank;return <tr key={p.id} className={`border-b ${['disqualified','locked'].includes(p.status)?'bg-red-100':''}`}><td className="p-3 font-black">{rank||'—'}</td><td className="p-3"><b>{p.name}</b><br/><span className="text-xs text-slate-500">{p.violation}</span></td><td className="p-3">{p.className}-{p.division}</td><td className="p-3">{p.progress||0}/{active.questionCount}</td><td className="p-3">{formatDuration(p.durationMs || 0)}</td><td className="p-3 font-black">{p.score == null?'Hidden':`${p.score}/${p.total}`}</td><td className="p-3 font-bold uppercase">{p.status}</td><td className="p-3">{['disqualified','locked'].includes(p.status)&&<button onClick={()=>unlock(p)} className="rounded bg-white px-3 py-2 font-bold text-red-700">Admin unlock</button>}</td></tr>})}</tbody></table>{!participants.length&&<p className="p-8 text-center text-slate-500">No students have joined.</p>}</div></div>}
    </section>
    {active && participants.length > 0 && <section className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="text-xl font-black">Time spent per question</h3><p className="mt-1 text-sm text-slate-500">Time is accumulated when a student uses Next, Previous, submits, or reaches the time limit.</p><div className="mt-5 space-y-3">{participants.map(student => <details key={student.id} className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-black text-slate-800">{student.name} · Class {student.className}-{student.division}</summary><div className="mt-4 grid gap-3 md:grid-cols-2">{quizQuestions.map((question, index) => <div key={question.id} className="rounded-lg bg-slate-50 p-3"><div className="flex items-start justify-between gap-3"><p className="text-sm font-bold">Q{index + 1}. {question.question}</p><span className="shrink-0 rounded bg-indigo-100 px-2 py-1 font-mono text-xs font-black text-indigo-700">{formatDuration(student.questionTimings?.[question.id] || 0)}</span></div></div>)}</div></details>)}</div></section>}
  </div>;
}
