import React, { useEffect, useMemo, useState } from 'react';
import { doc, getDoc, serverTimestamp, setDoc } from 'firebase/firestore';
import { db } from './firebase-init';
import { generateWebsitePerformanceReport } from './AdminReportGenerator';
import { auth, GoogleAuthProvider, signInWithPopup } from './firebase-auth';

const RANGE_OPTIONS = [['month', 'Current month'], ['previous', 'Previous month'], ['3m', 'Last 3 months'], ['6m', 'Last 6 months'], ['12m', 'Last year'], ['custom', 'Custom range']];
const SEO_DEFAULT = { title: '', description: '', keywords: '', canonical: '', ogTitle: '', ogDescription: '', ogImage: '', robots: 'index, follow', schema: '' };
const emptyMetrics = { clicks: null, impressions: null, ctr: null, position: null, users: null, sessions: null, pageViews: null, engagementRate: null, pages: [], queries: [], sources: [], devices: [], countries: [], trend: [] };

function iso(date) { return date.toISOString().slice(0, 10); }
const GOOGLE_SCOPES = ['https://www.googleapis.com/auth/webmasters.readonly', 'https://www.googleapis.com/auth/analytics.readonly'];
const SEARCH_SITE = 'https://ansarschool.in/';
const GA4_PROPERTY = '541890848';
async function googlePost(url, token, body) { const response = await fetch(url, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.error?.message || `Google returned ${response.status}`); } return response.json(); }
function gaReport(token, body) { return googlePost(`https://analyticsdata.googleapis.com/v1beta/properties/${GA4_PROPERTY}:runReport`, token, body); }
function datesFor(range, customStart, customEnd) {
  const now = new Date(); const end = new Date(now.getFullYear(), now.getMonth(), now.getDate()); let start = new Date(end);
  if (range === 'previous') { start = new Date(now.getFullYear(), now.getMonth() - 1, 1); return { start: iso(start), end: iso(new Date(now.getFullYear(), now.getMonth(), 0)) }; }
  if (range === 'month') start = new Date(now.getFullYear(), now.getMonth(), 1);
  if (range === '3m') start.setMonth(start.getMonth() - 3);
  if (range === '6m') start.setMonth(start.getMonth() - 6);
  if (range === '12m') start.setFullYear(start.getFullYear() - 1);
  return { start: range === 'custom' ? customStart : iso(start), end: range === 'custom' ? customEnd : iso(end) };
}
function displayMetric(value, suffix = '') { return value === null || value === undefined || value === '' ? '—' : `${Number(value).toLocaleString('en-IN', { maximumFractionDigits: 2 })}${suffix}`; }
function percent(value) { return value === null || value === undefined ? '—' : `${Number(value).toFixed(2)}%`; }
function normalize(raw = {}) { return { ...emptyMetrics, ...raw, pages: raw.pages || raw.topPages || [], queries: raw.queries || raw.topQueries || [], sources: raw.sources || [], devices: raw.devices || [], countries: raw.countries || raw.geography || [], trend: raw.trend || [] }; }
function BarList({ rows, label = 'name', value = 'value', empty = 'No data has been supplied for this period.' }) { const max = Math.max(...rows.map(x => Number(x[value]) || 0), 1); return rows.length ? <div className="space-y-3">{rows.slice(0, 8).map((row, i) => <div key={`${row[label] || row.path || i}`}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate font-semibold text-slate-700">{row[label] || row.path || row.url || 'Untitled'}</span><span className="font-bold text-slate-900">{displayMetric(row[value])}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${Math.max(3, (Number(row[value]) || 0) / max * 100)}%` }} /></div></div>)}</div> : <p className="py-5 text-sm text-slate-500">{empty}</p>; }

export default function AdminAnalytics() {
  const [tab, setTab] = useState('overview'); const [range, setRange] = useState('month');
  const [customStart, setCustomStart] = useState(iso(new Date(new Date().setMonth(new Date().getMonth() - 1)))); const [customEnd, setCustomEnd] = useState(iso(new Date()));
  const [metrics, setMetrics] = useState(emptyMetrics); const [status, setStatus] = useState('Loading analytics configuration…'); const [busy, setBusy] = useState(false);
  const [seoPath, setSeoPath] = useState('/'); const [seo, setSeo] = useState(SEO_DEFAULT); const [reportMessage, setReportMessage] = useState(''); const [googleToken, setGoogleToken] = useState('');
  const period = useMemo(() => datesFor(range, customStart, customEnd), [range, customStart, customEnd]);

  const connectGoogle = async () => { setBusy(true); setStatus('Opening secure Google sign-in...'); try { const provider = new GoogleAuthProvider(); GOOGLE_SCOPES.forEach(scope => provider.addScope(scope)); provider.setCustomParameters({ prompt: 'consent' }); const result = await signInWithPopup(auth, provider); const token = GoogleAuthProvider.credentialFromResult(result)?.accessToken; if (!token) throw new Error('Google did not return reporting access.'); setGoogleToken(token); } catch (error) { setStatus(`Google connection could not be completed: ${error.message}`); } finally { setBusy(false); } };

  const load = async () => {
    if (!period.start || !period.end) return; setBusy(true); setStatus('Loading available website data…');
    try {
      if (!googleToken) { setMetrics(emptyMetrics); setStatus('Connect your school Google account to load Search Console and GA4 data.'); return; }
      const searchUrl = `https://searchconsole.googleapis.com/webmasters/v3/sites/${encodeURIComponent(SEARCH_SITE)}/searchAnalytics/query`; const searchBody = { startDate: period.start, endDate: period.end }; const dateRanges = [{ startDate: period.start, endDate: period.end }];
      const [searchTotal, searchQueries, gaTotal, gaPages, gaSources, gaDevices, gaCountries] = await Promise.all([googlePost(searchUrl, googleToken, searchBody), googlePost(searchUrl, googleToken, { ...searchBody, dimensions: ['query'], rowLimit: 8 }), gaReport(googleToken, { dateRanges, metrics: [{ name: 'activeUsers' }, { name: 'sessions' }, { name: 'screenPageViews' }, { name: 'engagementRate' }] }), gaReport(googleToken, { dateRanges, dimensions: [{ name: 'pagePath' }], metrics: [{ name: 'screenPageViews' }, { name: 'activeUsers' }, { name: 'engagementRate' }], limit: 8, orderBys: [{ metric: { metricName: 'screenPageViews' }, desc: true }] }), gaReport(googleToken, { dateRanges, dimensions: [{ name: 'sessionDefaultChannelGroup' }], metrics: [{ name: 'sessions' }], limit: 8 }), gaReport(googleToken, { dateRanges, dimensions: [{ name: 'deviceCategory' }], metrics: [{ name: 'activeUsers' }], limit: 8 }), gaReport(googleToken, { dateRanges, dimensions: [{ name: 'country' }], metrics: [{ name: 'activeUsers' }], limit: 8 })]);
      const search = searchTotal.rows?.[0] || {}; const total = gaTotal.rows?.[0]?.metricValues || [];
      setMetrics(normalize({ clicks: Number(search.clicks || 0), impressions: Number(search.impressions || 0), ctr: Number(search.ctr || 0) * 100, position: Number(search.position || 0), users: Number(total[0]?.value || 0), sessions: Number(total[1]?.value || 0), pageViews: Number(total[2]?.value || 0), engagementRate: Number(total[3]?.value || 0) * 100, queries: (searchQueries.rows || []).map(row => ({ query: row.keys?.[0] || '(not set)', clicks: Number(row.clicks || 0) })), pages: (gaPages.rows || []).map(row => ({ path: row.dimensionValues?.[0]?.value || '/', views: Number(row.metricValues?.[0]?.value || 0), users: Number(row.metricValues?.[1]?.value || 0), engagementRate: Number(row.metricValues?.[2]?.value || 0) * 100 })), sources: (gaSources.rows || []).map(row => ({ name: row.dimensionValues?.[0]?.value || '(not set)', value: Number(row.metricValues?.[0]?.value || 0) })), devices: (gaDevices.rows || []).map(row => ({ name: row.dimensionValues?.[0]?.value || '(not set)', value: Number(row.metricValues?.[0]?.value || 0) })), countries: (gaCountries.rows || []).map(row => ({ country: row.dimensionValues?.[0]?.value || '(not set)', users: Number(row.metricValues?.[0]?.value || 0) })) })); setStatus(`Live data loaded for ${period.start} to ${period.end}.`);
    } catch (error) { setMetrics(emptyMetrics); setStatus(`Analytics could not be loaded: ${error.message}`); } finally { setBusy(false); }
  };
  useEffect(() => { load(); }, [period.start, period.end, googleToken]);
  useEffect(() => { (async () => { const saved = await getDoc(doc(db, 'seoPages', encodeURIComponent(seoPath))); setSeo(saved.exists() ? { ...SEO_DEFAULT, ...saved.data() } : { ...SEO_DEFAULT, canonical: `https://ansarschool.in${seoPath}` }); })(); }, [seoPath]);

  const saveSeo = async () => { setBusy(true); try { await setDoc(doc(db, 'seoPages', encodeURIComponent(seoPath)), { ...seo, path: seoPath, updatedAt: serverTimestamp() }, { merge: true }); setReportMessage('SEO settings saved. Publish/rebuild the website to apply static SEO changes.'); } catch (e) { setReportMessage(`Could not save SEO settings: ${e.message}`); } finally { setBusy(false); } };    const report = async (download = false) => {
    const reportData = { period, metrics, createdAt: serverTimestamp(), type: range, summary: `Website performance report for ${period.start} to ${period.end}.` };
    setBusy(true);
    try {
      const id = `${period.start}_${period.end}`;
      await setDoc(doc(db, 'analyticsReports', id), reportData, { merge: true });
      if (download) {
        const protocol = await generateWebsitePerformanceReport(metrics, { period, onProgress: () => {} });
        protocol.triggerDownload();
        setReportMessage('Report saved and downloaded as a PDF.');
      } else {
      setReportMessage('Report saved successfully.');
      }
    } catch (error) { setReportMessage(`Could not generate the report: ${error.message}`); }
    finally { setBusy(false); }
  };
  const cards = [['Users', metrics.users], ['Sessions', metrics.sessions], ['Page views', metrics.pageViews], ['Search clicks', metrics.clicks], ['Impressions', metrics.impressions], ['CTR', metrics.ctr, '%'], ['Avg. position', metrics.position], ['Engagement', metrics.engagementRate, '%']];
  const tabs = [['overview','Overview'], ['analytics','Analytics'], ['search','Search Performance'], ['pages','Top Pages'], ['seo','SEO Management'], ['performance','SEO Performance'], ['reports','Reports']];
  return <div className="space-y-6"><div className="rounded-2xl bg-gradient-to-br from-emerald-950 to-emerald-700 p-6 text-white shadow-lg"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-200">Website intelligence</p><h2 className="mt-1 text-3xl font-black">Analytics & SEO Centre</h2><p className="mt-2 max-w-2xl text-sm text-emerald-100">Google Analytics and Search Console data is displayed only when returned by your secure server-side bridge.</p></div><div className="flex flex-wrap gap-2"><select value={range} onChange={e => setRange(e.target.value)} className="rounded-lg border-0 bg-white px-3 py-2 text-sm font-bold text-slate-800">{RANGE_OPTIONS.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select>{range === 'custom' && <><input type="date" value={customStart} onChange={e => setCustomStart(e.target.value)} className="rounded-lg px-2 py-2 text-sm text-slate-800" /><input type="date" value={customEnd} onChange={e => setCustomEnd(e.target.value)} className="rounded-lg px-2 py-2 text-sm text-slate-800" /></>}<button onClick={load} disabled={busy} className="rounded-lg bg-amber-300 px-4 py-2 text-sm font-black text-emerald-950">{busy ? 'Loading…' : 'Refresh'}</button></div></div></div>
    <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-bold ${tab === id ? 'bg-emerald-600 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{label}</button>)}</div>
    <div className="rounded-xl border border-sky-100 bg-sky-50 px-4 py-3 text-sm text-sky-800">{status}</div>
    {!googleToken && <button onClick={connectGoogle} disabled={busy} className="rounded-lg bg-emerald-600 px-5 py-3 text-sm font-bold text-white">Connect Google Analytics & Search Console</button>}
    {tab !== 'seo' && <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label,value,suffix]) => <div key={label} className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-900">{displayMetric(value, suffix)}</p></div>)}</div>}
    {(tab === 'overview' || tab === 'analytics') && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><h3 className="font-extrabold text-slate-900">Traffic sources</h3><div className="mt-5"><BarList rows={metrics.sources} /></div></section><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><h3 className="font-extrabold text-slate-900">Device breakdown</h3><div className="mt-5"><BarList rows={metrics.devices} /></div></section></div>}
    {(tab === 'overview' || tab === 'pages') && <section className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="border-b p-6"><h3 className="font-extrabold text-slate-900">Most visited pages</h3><p className="mt-1 text-sm text-slate-500">Ranking is based on the selected reporting period.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">#</th><th className="p-4">Page</th><th className="p-4">Views</th><th className="p-4">Users</th><th className="p-4">Engagement</th></tr></thead><tbody>{metrics.pages.length ? metrics.pages.map((p,i) => <tr key={p.path || p.url || i} className="border-t"><td className="p-4 font-bold">{i+1}</td><td className="p-4 font-semibold">{p.path || p.url || p.name}</td><td className="p-4">{displayMetric(p.views ?? p.value)}</td><td className="p-4">{displayMetric(p.users)}</td><td className="p-4">{percent(p.engagementRate)}</td></tr>) : <tr><td colSpan="5" className="p-8 text-center text-slate-500">No page analytics available for this period.</td></tr>}</tbody></table></div></section>}
    {(tab === 'search' || tab === 'performance') && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><h3 className="font-extrabold">Top search queries</h3><div className="mt-5"><BarList rows={metrics.queries} label="query" value="clicks" /></div></section><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><h3 className="font-extrabold">Geographic performance</h3><div className="mt-5"><BarList rows={metrics.countries} label="country" value="users" /></div></section></div>}
    {tab === 'seo' && <section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h3 className="text-xl font-extrabold">Page SEO settings</h3><p className="mt-1 text-sm text-slate-500">These records are admin-only. Static metadata is applied when the site is published.</p></div><input value={seoPath} onChange={e => setSeoPath(e.target.value.startsWith('/') ? e.target.value : `/${e.target.value}`)} className="rounded-lg border border-slate-200 px-3 py-2 font-mono text-sm" placeholder="/page-path" /></div><div className="mt-6 grid gap-4 md:grid-cols-2">{[['title','Page title'],['description','Meta description'],['keywords','Keywords'],['canonical','Canonical URL'],['ogTitle','Open Graph title'],['ogDescription','Open Graph description'],['ogImage','Social sharing image URL'],['robots','Robots / indexing']].map(([key,label]) => <label key={key} className="text-sm font-bold text-slate-700">{label}{key.includes('description') ? <textarea value={seo[key]} onChange={e=>setSeo({...seo,[key]:e.target.value})} className="mt-1 h-24 w-full rounded-lg border border-slate-200 p-3 font-normal" /> : <input value={seo[key]} onChange={e=>setSeo({...seo,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-200 p-3 font-normal" />}</label>)}<label className="text-sm font-bold text-slate-700 md:col-span-2">Structured data (valid JSON-LD only)<textarea value={seo.schema} onChange={e=>setSeo({...seo,schema:e.target.value})} className="mt-1 h-28 w-full rounded-lg border border-slate-200 p-3 font-mono text-xs font-normal" /></label></div><button onClick={saveSeo} disabled={busy} className="mt-5 rounded-lg bg-emerald-600 px-5 py-3 font-bold text-white">Save SEO settings</button></section>}
    {tab === 'reports' && <section className="space-y-6 rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div><h3 className="text-xl font-extrabold">Management reports</h3><p className="mt-2 max-w-2xl text-sm text-slate-600">Reports use the selected period and verified live data.</p><div className="mt-5 flex flex-wrap gap-3"><button onClick={() => report(false)} className="rounded-lg bg-slate-900 px-5 py-3 font-bold text-white">Save report</button><button onClick={() => report(true)} className="rounded-lg bg-emerald-600 px-5 py-3 font-bold text-white">Download PDF</button></div></div><div className="border-t pt-6"><h4 className="font-extrabold text-slate-900">Secure data bridge</h4><p className="mt-1 text-sm text-slate-500">Search Console and Google Analytics data is requested through the protected Firebase reporting service. No credentials or bridge URL are stored in the browser.</p></div></section>}
    {reportMessage && <p className="rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{reportMessage}</p>}</div>;
}
