import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { doc, onSnapshot } from 'firebase/firestore';
import Layout from './Layout';
import { db } from './firebase-init';
import { applySeoMetadata } from './seoUtils';
import { DEFAULT_ALUMNI_SETTINGS, googleDrivePreviewUrl, mergeAlumniSettings } from './alumniContent';

function AlumniImage({ url, title, index, priority = false, contain = false }) {
  if (url) return <img src={url} alt={`${title}${index ? ` — image ${index}` : ''}`} className={`aspect-[4/3] h-full w-full rounded-2xl ${contain ? 'bg-slate-100 object-contain p-2' : 'object-cover'}`} loading={priority ? 'eager' : 'lazy'} />;
  return <div className="flex aspect-[4/3] min-h-48 flex-col items-center justify-center rounded-2xl border-2 border-dashed border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-amber-50 px-5 text-center"><svg className="h-10 w-10 text-emerald-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="m3 16 4.5-4.5a2 2 0 0 1 2.8 0L14 15.2l1.5-1.5a2 2 0 0 1 2.8 0L21 16.4M5 20h14a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2Zm10-11h.01" /></svg><p className="mt-3 text-xs font-black uppercase tracking-[.2em] text-emerald-700">Image space{index ? ` ${index}` : ''}</p><p className="mt-2 text-sm font-bold text-slate-500">{title}</p></div>;
}

function AlumniCard({ item, number, href }) {
  const images = item.imageUrls?.length ? item.imageUrls : [''];
  return <article className="flex flex-col overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className={`grid gap-3 p-3 ${images.length > 1 ? 'sm:grid-cols-2' : ''}`}>{images.map((url, i) => <AlumniImage key={i} url={url} title={item.title} index={images.length > 1 ? i + 1 : null} />)}</div><div className="flex flex-1 flex-col p-6 pt-4 sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-600">Alumni story {String(number).padStart(2, '0')}</p><h3 className="mt-3 text-2xl font-extrabold text-slate-900">{item.title}</h3>{item.subtitle && <p className="mt-2 font-extrabold text-emerald-700">{item.subtitle}</p>}{item.speaker && <p className="mt-3 text-sm font-bold leading-relaxed text-slate-700">{item.speaker}</p>}<p className="mt-4 leading-relaxed text-slate-600">{item.body}</p><Link to={href} className="mt-6 inline-flex w-fit items-center rounded-xl bg-emerald-700 px-5 py-3 text-sm font-extrabold text-white transition hover:bg-emerald-800">Read full article <span className="ml-2" aria-hidden="true">→</span></Link></div></article>;
}

export default function Alumni() {
  const [settings, setSettings] = useState(DEFAULT_ALUMNI_SETTINGS);
  useEffect(() => onSnapshot(doc(db, 'settings', 'alumniPage'), snap => snap.exists() && setSettings(mergeAlumniSettings(snap.data())), () => setSettings(DEFAULT_ALUMNI_SETTINGS)), []);
  useEffect(() => { applySeoMetadata({ title: 'Ansar Alumni | Ansar English School', description: settings.introText, keywords: 'Ansar English School alumni, alumni success stories, Ansar Alumni International Qatar' }, '/alumni'); }, [settings.introText]);
  if (settings.published === false) return <Layout><div className="py-24 text-center"><h1 className="text-3xl font-extrabold text-slate-900">Alumni page coming soon</h1></div></Layout>;
  return <Layout fullWidth><main className="bg-slate-50">
    <section className="relative isolate overflow-hidden bg-emerald-950 text-white"><img src={settings.heroImageUrl} alt="Ansar English School alumni" className="absolute inset-0 -z-10 h-full w-full object-cover opacity-35" fetchPriority="high" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-emerald-950 via-emerald-950/90 to-slate-950/40"/><div className="mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 lg:py-32"><p className="text-sm font-extrabold uppercase tracking-widest text-amber-300">{settings.eyebrow}</p><h1 className="mt-4 max-w-4xl text-5xl font-extrabold leading-tight sm:text-6xl lg:text-7xl">{settings.heroTitle}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-emerald-50/90 lg:text-xl">{settings.heroSubtitle}</p></div></section>
    <section className="mx-auto max-w-4xl px-4 py-16 text-center sm:px-6 lg:py-24"><p className="text-sm font-black uppercase tracking-[.2em] text-amber-600">A lifelong connection</p><h2 className="mt-3 text-3xl font-extrabold text-slate-900 lg:text-5xl">{settings.introTitle}</h2><p className="mt-6 text-lg leading-8 text-slate-600">{settings.introText}</p></section>
    <section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 lg:px-8"><p className="text-sm font-black uppercase tracking-[.2em] text-amber-600">Events</p><h2 className="mt-2 text-3xl font-extrabold text-slate-900 lg:text-4xl">Alumni who return to inspire</h2><div className="mt-8 grid gap-7 lg:grid-cols-2">{settings.events.map((item, i) => <AlumniCard key={`${item.title}-${i}`} item={item} number={i + 1} href={`/alumni/events/${i}`} />)}</div></section>
    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-sm font-black uppercase tracking-[.2em] text-amber-600">Success stories</p><h2 className="mt-2 text-3xl font-extrabold text-slate-900 lg:text-4xl">Journeys that make us proud</h2><div className="mt-8 grid gap-7 lg:grid-cols-3">{settings.successStories.map((item, i) => <AlumniCard key={`${item.title}-${i}`} item={item} number={i + 1} href={`/alumni/success-stories/${i}`} />)}</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-8 px-4 py-20 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div className="rounded-3xl bg-emerald-950 p-8 text-white shadow-xl sm:p-10"><p className="text-sm font-black uppercase tracking-[.2em] text-amber-300">Networking & giving back</p><h2 className="mt-3 text-3xl font-extrabold lg:text-4xl">{settings.thanalTitle}</h2><p className="mt-6 leading-8 text-emerald-50/90">{settings.thanalText}</p></div><div className="rounded-3xl border border-emerald-100 bg-white p-8 shadow-sm"><h3 className="text-2xl font-extrabold text-slate-900">Where our contributions go</h3><ul className="mt-6 space-y-5">{settings.contributions.map((item, i) => <li key={`${item.title}-${i}`} className="flex gap-4"><span className="flex h-8 w-8 flex-none items-center justify-center rounded-full bg-amber-100 text-sm font-black text-amber-700">{i + 1}</span><p className="text-sm leading-6 text-slate-600"><strong className="block text-base text-slate-900">{item.title}</strong>{item.body}</p></li>)}</ul></div></section>
    <section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 lg:px-8"><div className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="grid gap-3 p-3 sm:grid-cols-2">{settings.givingBackImageUrls.map((url, i) => <AlumniImage key={i} url={url} title={settings.givingBackTitle} index={i + 1} contain />)}</div><div className="p-8 sm:p-10"><p className="text-sm font-black uppercase tracking-[.2em] text-amber-600">Community initiative</p><h2 className="mt-3 text-3xl font-extrabold text-slate-900">{settings.givingBackTitle}</h2><p className="mt-5 leading-8 text-slate-600">{settings.givingBackText}</p></div></div></section>
    <section className="bg-emerald-950 py-20 text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-sm font-black uppercase tracking-[.2em] text-amber-300">Alumni PDF</p><div className="mt-3 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-3xl font-extrabold lg:text-4xl">{settings.pdfTitle}</h2><p className="mt-3 max-w-3xl text-emerald-50/80">{settings.pdfDescription}</p></div><a href={settings.pdfUrl} target="_blank" rel="noopener noreferrer" className="inline-flex flex-none items-center justify-center rounded-xl bg-amber-400 px-5 py-3 text-sm font-extrabold text-emerald-950 hover:bg-amber-300">Open PDF</a></div><div className="mt-8 overflow-hidden rounded-2xl bg-white shadow-2xl"><iframe title={settings.pdfTitle} src={googleDrivePreviewUrl(settings.pdfUrl)} className="h-[38rem] w-full border-0" allow="autoplay" /></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="rounded-3xl bg-gradient-to-r from-amber-50 to-emerald-50 p-8 sm:flex sm:items-center sm:justify-between sm:gap-6"><div><p className="text-sm font-black uppercase tracking-[.2em] text-amber-700">Alumni directory</p><h2 className="mt-2 text-2xl font-extrabold text-slate-900">Alumni in Prominent Positions</h2></div><a href={settings.prominentPositionsUrl} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white hover:bg-emerald-800 sm:mt-0">View alumni profiles</a></div></section>
  </main></Layout>;
}
